obj-$(CONFIG_TEST_atmegaX8_GPIO)	:= atmegaX8_gpio.o
obj-$(CONFIG_TEST_lm4f120_CPU)		:= lm4f120h5qr_cpu.o
obj-$(CONFIG_TEST_lm4f120_GPIO)		:= lm4f120h5qr_gpio.o
obj-$(CONFIG_TEST_msp430f21x1_GPIO)	:= msp430f21x1_gpio.o
