obj-$(CONFIG_DEV_CPU0)	+= cpu0.o
obj-$(CONFIG_DEV_GPIO0)	+= gpio0.o
obj-$(CONFIG_DEV_GPIO1)	+= gpio1.o
obj-$(CONFIG_DEV_GPIO2)	+= gpio2.o
obj-$(CONFIG_DEV_GPIO3)	+= gpio3.o
obj-$(CONFIG_DEV_GPIO4)	+= gpio4.o
obj-$(CONFIG_DEV_GPIO5)	+= gpio5.o
